### ISSUE TITLE
spider cocoon in the broodmother encounter is setting player hp to 1 when popped. Possibly have to do with 7.30 venomancer changes

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/pathfinders#11]
Opened from Discord by **FRIDAY#8768**
Follow the conversation [here](https://discord.com/channels/501306949434867713/876970971007971358/878220908991492157)

**Comment by fcalife** [comment]
Duplicate of https://github.com/arcadia-redux/pathfinders/issues/16
