### ISSUE TITLE
Adapt collection from CHC: implementation details

### ISSUE THREAD

**Issue by fcalife** [arcadia-redux/pathfinders#22]
All relevant data, where necessary, about this issue can be found [in this spreadsheet](https://docs.google.com/spreadsheets/d/1Z1RbscpFKvyQShrDkWugA00KY8R96mHA9WoCbL0oWkE/edit?usp=sharing).

Pathfinders' collection will work **very similarly to CHC**. What changes?

Pathfinders only has the following categories (+chests):

![dota2_3klPDpCedA](https://user-images.githubusercontent.com/7921728/130906769-f2cb4fc2-81d0-45aa-bb91-3e5cc9576054.png)

They should be called "auras", "skins", "couriers", "kill effects", "cosmetic abilities", and "sprays".

- Pathfinders only uses one currency: arcane fragments (fragments for short) ![image](https://user-images.githubusercontent.com/7921728/130906444-8ec4fb13-ca31-44e8-a5a7-5a7e71b00eed.png)
- Players gain fragments by playing, by buying a subscription (same as chc boost), or by buying them directly from the store.
- Tier 1 subscription: $3.99, **3,000 fragments**
- Tier 2 subscription: $19.99, **20,000 fragments**
- Shop prices:

![image](https://user-images.githubusercontent.com/7921728/130906730-56551806-ae58-4e54-80b1-26988ec81a9a.png)

Subscribers benefits:
- +1 life at the start of the game and +1 max life
- big list of subscriber-only cosmetics (mostly cosmetic abilities and sprays), different for T1 and T2:

![image](https://user-images.githubusercontent.com/7921728/130906945-175664ff-eb87-4282-b354-c37674b320f6.png)

note: list above is not complete, see spreadsheet for full list.

**Comment by Sheodar** [comment]
Implented
